---
abstract: 'lightweight configuration file manager that uses Pure Perl to serialize.'
author:
  - 'punytan <punytan@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-PP
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Data::Dumper: 0
  Exporter: 0
  File::Spec: 3.33
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/punytan/p5-Config-PP.git
version: 0.03
